language: python

python: 2.7

env:
    - TOXENV=py27-d9
    - TOXENV=py35-d9
    - TOXENV=py27-d10
    - TOXENV=py35-d10
    - TOXENV=cov

# python:
#   - 2.7
#   - 3.5
#   - 3.6
#
# matrix:
#   exlcude:
#     - python: 2.7
#       env: 
#     - python 3.5
#       env:
#     - python: 3.6
#       env:
#
#   include:
#     - python: 2.7
#       env: TOXENV=py27-d9
#     - python: 2.7
#       env: TOXENV=py27-d10
#     - python: 2.7
#       env: TOXENV=cov
#
#     - python: 3.5
#       env: TOXENV=py35-d9
#     - python: 3.5
#       env: TOXENV=py35-d10
#     - python: 3.5
#       env: TOXENV=py35-d11
#     - python: 3.5
#       env: TOXENV=cov
#
#     - python: 3.6
#       env: TOXENV=py36-d11
#     - python: 3.6
#       env: TOXENV=py36-d20
#     - python: 3.6
#       env: TOXENV=cov

branches:
    only:
        - master
        - develop

install: pip install --quiet tox

script: tox

after_script:
    - if [ $TOXENV == "cov" ]; then
        pip install --quiet coveralls;
        coveralls;
      fi
