language: python

python: 2.7

env:
    - TOXENV=py27-d17
    - TOXENV=py34-d17
    - TOXENV=py27-d18
    - TOXENV=py34-d18
    - TOXENV=py27-d19
    - TOXENV=py34-d19
    - TOXENV=cov

branches:
    only:
        - master
        - develop

install: pip install --quiet --use-mirrors tox

script: tox

after_script:
    - if [ $TOXENV == "cov" ]; then
        pip install --quiet --use-mirrors coveralls;
        coveralls;
      fi
