language: python

python: 2.7

env:
    - TOXENV=py27-d10
    - TOXENV=py35-d10
    - TOXENV=py27-d11
    - TOXENV=py35-d11
    - TOXENV=cov

branches:
    only:
        - master
        - develop

install: pip install --quiet tox

script: tox

after_script:
    - if [ $TOXENV == "cov" ]; then
        pip install --quiet coveralls;
        coveralls;
      fi
